# Kubernetes kubectl installation: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
- name: Install kubectl for Debian/Ubuntu
  when: ansible_pkg_mgr == "apt"
  block:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install packages needed to use the Kubernetes apt repository
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
      become: true

    - name: Ensure keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
      become: true

    - name: Download the public signing key for the Kubernetes package repositories
      ansible.builtin.shell: |
        set -o errexit -o pipefail
        curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version_minor }}/deb/Release.key \
          | gpg --dearmor -o {{ kubernetes_keyring_path }}
      args:
        executable: /bin/bash
        creates: "{{ kubernetes_keyring_path }}"
      become: true

    - name: Set correct permissions for Kubernetes keyring
      ansible.builtin.file:
        path: "{{ kubernetes_keyring_path }}"
        mode: "0644"
        owner: root
        group: root
      become: true

    - name: Add the Kubernetes apt repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          deb [signed-by={{ kubernetes_keyring_path }}] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version_minor }}/deb/ /
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Update APT package index
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present
      become: true

- name: Install kubectl for Archlinux
  when: ansible_pkg_mgr == "pacman"
  block:
    - name: Update pacman package database
      ansible.builtin.pacman:
        update_cache: true
      become: true

    - name: Install kubectl
      ansible.builtin.pacman:
        name: kubectl
        state: present
      become: true
  tags:
    - kubernetes
    - installation

- name: Verify kubectl installation
  ansible.builtin.command: kubectl version --client
  register: kubernetes_kubectl_version_check
  changed_when: false
  failed_when: kubernetes_kubectl_version_check.rc != 0
  tags:
    - kubernetes
    - verification
